USE TpCuatrimestralMoruzziQuinteros
--Tipo de producto
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Bebida sin alcohol')
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Bebida con alcohol')
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Entrada')
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Menu infantil')
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Plato principal')
INSERT INTO TipoDeProducto(Descripcion) VALUES ('Postre')
--Producto
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,190,100,1,'Gaseosa Coca-Cola 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,320,200,1,'Gaseosa Coca-Cola 1.75L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,140,100,1,'Agua mineral 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,220,100,1,'Agua mineral 1 L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,150,100,1,'Agua saborizada 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(1,260,200,1,'Agua saborizada 1.5L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,220,100,1,'Cerveza Brahma 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,220,100,1,'Cerveza Quilmes 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,260,100,1,'Cerveza Stella Artois 500ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,350,200,1,'Cerveza Brahma 1 L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,350,100,1,'Cerveza Quilmes 1 L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,380,100,1,'Cerveza Stella Artois 1 L')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,720,100,1,'Vino Alaris Malbec')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,720,100,1,'Vino Blanco Cafayate')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,240,100,1,'Corona Porron')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,540,100,1,'Patagonia 730 ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(2,340,100,1,'Patagonia Lata 473ml')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,660,80,1,'Bastoncitos de mozzarella')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,1200,80,1,'Rabas a la Romana')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,900,80,1,'Tortilla de papa rellena de JyQ')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,600,80,1,'Buñuelos de acelga')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,960,80,1,'Picada para dos personas')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,1700,80,1,'Picada para cuatro personas')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,540,80,1,'Papas fritas simples')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,560,80,1,'Papas fritas provenzal')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,670,80,1,'Papas fritas con cheddar')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(3,700,80,1,'Papas fritas con cheddar y Bacon')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(4,300,80,1,'Plato Spagetti pequeño')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(4,350,80,1,'Hamburguesa pequeña')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(4,320,80,1,'Nuggets de pollo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(4,330,80,1,'Milanesa de pollo con fritas')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,660,60,1,'Cheese burger')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,850,60,1,'Doble Cheese burger')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,880,60,1,'Blues Burger')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,880,60,1,'Dambo Burger')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,830,60,1,'Veggie Burger')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,960,60,1,'Triple Bacon')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,720,60,1,'Ensalada Cesar')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,690,60,1,'Ensalada Veggie')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,830,60,1,'Wok Veggie')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,870,60,1,'Wok de Pollo Teriyaki')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,950,60,1,'Wok de Carne')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,830,60,1,'Pizza de Mozzarella')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,990,60,1,'Pizza Jamon y Morrones')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1000,60,1,'Pizza Napolitana')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,960,60,1,'Pizza Fugazzeta con queso')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1070,60,1,'Pizza Roquefort y Verdeo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1070,60,1,'Pizza Cuatro Quesos')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1070,60,1,'Pizza panceta y verdeo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1020,60,1,'Pizza Mitad y Mitad')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1500,60,1,'Asado Banderita')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1680,60,1,'Vacio Porcion')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1500,60,1,'Bife de Chorizo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,325,60,1,'Chorizo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,360,60,1,'Choripan')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,660,60,1,'Canelones de Pollo y Verdura')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,440,60,1,'Penne Rigate Italianos')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,540,60,1,'Sorrentnos de Calabaza')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,950,60,1,'Lasagna de Berenjenas')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,460,60,1,'Noquis de Papa')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1020,60,1,'Cuadril Sandwich')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,890,60,1,'Ciabatta de Pollo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1145,60,1,'Super Mila Sandwich')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1320,60,1,'Ribs de Cerdo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,1260,60,1,'Bondiola Caramelizada')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,960,60,1,'Milanesa de Ternera')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(5,880,60,1,'Suprema de Pollo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(6,480,50,1,'Tiramisu')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(6,480,50,1,'Cheesecake Oreo')
INSERT INTO Producto(IdTipoProducto,Precio,Stock,Estado,DescripcionPlato) VALUES(6,480,50,1,'Cheesecake Frutos Rojos')
--Metodo Pago
INSERT INTO MetodoPago(ID,Descripcion) VALUES('D','Debito');
INSERT INTO MetodoPago(ID,Descripcion) VALUES('T','Tarjeta');
INSERT INTO MetodoPago(ID,Descripcion) VALUES('E','Efectivo');







